import {
    AlertTriangle,
    ArrowDown,
    ArrowRight,
    ArrowUp,
    ArrowUpDown,
    BriefcaseBusiness,
    Building,
    Calendar,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Construction,
    DollarSign,
    Dot,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FileText,
    Gem,
    Globe,
    GraduationCap,
    Home,
    Info,
    Instagram,
    Key,
    LayoutDashboard,
    LifeBuoy,
    Lightbulb,
    Link,
    Loader2,
    LogIn,
    LogOut,
    Mail,
    MapPin,
    Menu,
    MoreHorizontal,
    PersonStanding,
    Plus,
    Rocket,
    Search,
    Shield,
    SlidersHorizontal,
    Tag,
    Target,
    Ticket,
    TrendingUp,
    Twitter,
    User,
    Users,
    X,
    Youtube,
    Zap,
    type IconNode as LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
    lightbulb: Lightbulb,
    graduationCap: GraduationCap,
    target: Target,
    zap: Zap,
    shield: Shield,
    checkCircle: CheckCircle,
    rocket: Rocket,
    arrowRight: ArrowRight,
    search: Search,
    trendingUp: TrendingUp,
    building: Building,
    ticket: Ticket,
    tag: Tag,
    document: FileText,
    globe: Globe,
    link: Link,
    mail: Mail,
    dollar: DollarSign,
    key: Key,
    plus: Plus,
    moreHor: MoreHorizontal,
    sliderHor: SlidersHorizontal,
    arrowDown: ArrowDown,
    arrowUp: ArrowUp,
    arrowUpDown: ArrowUpDown,
    briefcaseBusiness: BriefcaseBusiness,
    personStanding: PersonStanding,
    users: Users,
    calendar: Calendar,
    mapPin: MapPin,
    construction: Construction,
    home: Home,
    gem: Gem,
    dashboard: LayoutDashboard,
    logout: LogOut,
    user: User,
    menu: Menu,
    externalLink: ExternalLink,
    dot: Dot,
    check: Check,
    cross: X,
    hide: EyeOff,
    view: Eye,
    chevronUp: ChevronUp,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    spinner: Loader2,
    warning: AlertTriangle,
    login: LogIn,
    briefcase: BriefcaseBusiness,
    diamond: Gem,
    lifeBuoy: LifeBuoy,
    info: Info,
    facebook: Facebook,
    twitter: Twitter,
    youtube: Youtube,
    instagram: Instagram,
};
